# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.411
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Register package
      run: dotnet nuget add source --username wrobel604 --password ${{ secrets.GITHUBTOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/wrobel604/index.json"
    - name: Create package
      run: dotnet pack PublishNugetTester --configuration Release
    - name: Push package
      run: dotnet nuget push "PublishNugetTester/bin/Release/PublishNugetTester.1.0.0.nupkg" --api-key ${{ secrets.GITHUBTOKEN }} --source "github"
